### PR TITLE
add cool navbar

### PR DESCRIPTION
**Pull request by UpTiGamer**

### CODE REVIEW

**Comment by UpTiGamer** [comment]
@Thedogecraft @3kh0 @M1noa ADD

**Comment by Thedogecraft** [comment]
Bro this is the old repo latest is v3 [Here](https://github.com/parcoil/nativegames.net)

**Comment by UpTiGamer** [comment]
@Thedogecraft it is for the older version so they can receive updates for a bit kind of like how node.js has long term support

**Comment by M1noa** [comment]
The LTS on node is not a version that still gets updates, its a version
that you can install and wont need to update from it for awhile, Ubunto and
many other things have LTS.

**Comment by UpTiGamer** [comment]
> The LTS on node is not a version that still gets updates, its a version that you can install and wont need to update from it for awhile, Ubunto and many other things have LTS.
> […](#)

it gets updates.... literally look it up

**Pull request closed without merging**
